### PR TITLE
URL-encode GitHub reference

### PR DESCRIPTION
**Pull request by krlmlr**
in install_github().

Use case:

``` r
install_github("krlmlr/ranger/ranger-r-package/ranger@b-#118-dimnames")
```

(The dash in `#118` is the offender.)

Also affects devtools, CC @jimhester @hadley.

### CODE REVIEW

**Comment by krlmlr** [comment]
Could you please review?

**Comment by gaborcsardi** [comment]
Thanks, looks good, but you don't seem to use vlapply, so maybe we can remove that for now.

**Comment by gaborcsardi** [comment]
Thanks!

**Comment by krlmlr** [comment]
@gaborcsardi: Do you plan a CRAN release anytime soon? I tend to use the dash in branch names...

**Comment by gaborcsardi** [comment]
@krlmlr I don't mind, but it depends on `crancache` now. :(

**Comment by krlmlr** [comment]
I learned a lesson: Release to CRAN before adding a dependency :/

**Comment by gaborcsardi** [comment]
I think that's a good lesson, but does not help *this* situation.

It is actually trivial to temporarily remove the dependency, let me do it quickly.

**Comment by gaborcsardi** [comment]
Just submitted to CRAN.

**Comment by krlmlr** [comment]
Awesome, thanks!

**Pull request merged**
